# Generated by Django 6.0.2 on 2026-03-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_lesson_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Время последней отправки уведомления",
            ),
        ),
    ]
