# Generated by Django 6.0.2 on 2026-03-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_course_last_notification_sent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="last_notification_sent",
        ),
    ]
